# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: local
      # defualt user: postgres
    ports:
      - 5432:5432

    volumes:
      - postgres_db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_db:
    driver: local
